# -*- coding: utf-8 -*-
"""Avg number of trails to get all  6 sides of dice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P6cQah8diU2CfvunMRHUYI40S0FpyyX4
"""

from numpy.lib.function_base import average
import numpy as np
import random
my_average=[]

for i in range(0,10000):
    nums = set((1,2,3,4,5,6))
    data =[]
    while nums:
        n=random.randint(1,6)
        data.append(n)
       


        if n in nums:
            nums.remove(n)
          
    x = len(data)
    # print(data)
    my_average.append(x)
print(np.mean(my_average))

