# -*- coding: utf-8 -*-
"""Filter,Map,Reduce.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t1eUYckX5jsHgUWRlEcEjvOB3VG-Q4x7

#Filter()
"""

'''Python's filter() is a built-in function that allows you to process
 an iterable and extract those items that satisfy a given condition. 
 This process is commonly known as a filtering operation.'''
#finding of even numbers using filter() from a list
def is_even(n):
  return n %2 ==0

nums=[3,4,7,4,8,9,5,8,6,2,6,8,9]

evens=list(filter(is_even,nums))
print(evens)

# same we can do by using lambda function
nums=[3,4,7,4,8,9,5,8,6,2,6,8,9]
evens=list(filter(lambda n:n%2==0,nums))
print(evens)



"""#Map()"""

'''What is map function in Python with example?
Python map() is a built-in function that applies a function on all the items
 of an iterator given as input. An iterator,
 for example, can be a list, a tuple, a string, etc. and it returns an iterable map object.'''


 # double the elements in list using map()

double=list(map(lambda n : n*2,evens))
print(double)

#square of each element in list
n=[4,5,6,3]
print(list(map(lambda x:x**2,n)))



"""#reduce()"""

'''Python's reduce() is a function that implements a mathematical technique called folding
 or reduction. reduce() is useful when you need to apply a function to an iterable and reduce
  it to a single cumulative value.'''

  # sum of all the numbers
  # in python reduce funtion is in functools so we need import
from functools import reduce
sum=reduce(lambda a,b : a+b, double)
print(sum)

