# -*- coding: utf-8 -*-
"""matrics creation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NUft270lqKxnkrwzjmIN6pkireVoa9Wd
"""

from numpy import*
# * means importing everything from numpy

m=matrix('1 2 3;44 5 5; 6 6 7; 8 9 9')
m

print(diagonal(m)) # to get the diagonal of matrix
print(m.min(), "is the min value in matrix") # to get min value in matrix
print(m.max(), "is the max value in matrix") # to get max value in matrix

"""#Adding matrices ,Multiplication"""

m1=matrix('1 2 3;44 5 5; 6 6 7')
m2=matrix('4 2 3;4 6 5; 6 6 7')
print(m1) # matrix m1
print(m2) # matrix m2
# adding m1 and m2 matrices
m=m1+m2
print("adding m1 and m2 matrices")
print(m)
# multipling m1 and m2 matrices
mat=m1*m2
print("multipling m1 and m2 matrices")
print(mat)

